name       : python-gtts-token
version    : 1.1.3
release    : 2
source     :
    - https://files.pythonhosted.org/packages/e7/25/ca6e9cd3275bfc3097fe6b06cc31db6d3dfaf32e032e0f73fead9c9a03ce/gTTS-token-1.1.3.tar.gz : 9d6819a85b813f235397ef931ad4b680f03d843c9b2a9e74dd95175a4bc012c5
license    : MIT
component  : programming.python
summary    : Calculates a token to run the Google Translate text to speech
description: |
    gTTS-token (Google Text to Speech token) is a python implementation of the token validation required by Google Translate when making a request to its translate API.
builddeps  :
    - python-requests
rundeps    :
    - python-requests
build      : |
    %python3_setup
install    : |
    %python3_install
check      : |
    %python3_test
